# PARITIONING ALGORITHM (START TO FINISH)
setwd("/Users/emwu9912/Documents/CU Anschutz/Employment/COVID-19 Modeling Group")

source("./CSTE/Partitioning/rmw_indiv_states.R")
source("./CSTE/Partitioning/comm_detection_rmw_co.R")
source("./CSTE/Partitioning/comm_detection_rmw_id.R")
source("./CSTE/Partitioning/comm_detection_rmw_mt.R")
source("./CSTE/Partitioning/comm_detection_rmw_nm.R")
source("./CSTE/Partitioning/comm_detection_rmw_ut.R")
source("./CSTE/Partitioning/comm_detection_rmw_wy.R")
